### ISSUE TITLE
Zainicjuj-logowanie-na-poziomie-backendu

### ISSUE THREAD

**Issue by ZimmerPM** [Tomasz-Zdeb/Team-Project-Class-Project#16]
Implementacja procesu logowania użytkownika do aplikacji

## Kryteria akceptacji
- [x] funkcjonalność logowania użytkownika została zaimplementowana z wykorzystaniem JWT
- [x] endpoint /token generuje i zwraca access token oraz refresh token po otrzymaniu poprawnych danych logowania
- [x] endpoint /token/refresh zwraca nowy zestaw tokenów  po podaniu refresh tokena
- [x] refresh token trafia na czarną listę po wylogowaniu (endpoint logout/), co uniemożliwia jego dalsze wykorzystanie
- [x] zmiany znajdują się na branchu `main'

**Comment by ZimmerPM** [comment]
Korzystając z tego, że na ZTPAI właśnie jest omawiane logowanie z użyciem tokenów JWT - proponuję, żeby tez od razu zastosować to w naszej aplikacji - dlatego myślę, że przeniesiemy to zadanie do kolejnego sprintu.

**Comment by Tomasz-Zdeb** [comment]
@ZimmerPM Możesz opisać trochę bardziej szczegółowo w kryteriach akceptacji jak ma wyglądać stan apki po realizacji tego zadania, bo to jest taki boilerplate który można użyć w każdym zadaniu :)
