### ISSUE TITLE
Stworz-widok-menu

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Team-Project-Class-Project#20]
Widok z pozycjami z karty menu

## Kryteria akceptacji
- [ ] widok z menu został utworzony
- [ ] menu w postaci listy/tabeli
- [ ] zmiany znajdują się na branchu `main`

**Comment by Tomasz-Zdeb** [comment]
Możnaby dodać do kryteriów akceptacji to co ustaliliśmy jeszcze na spotkaniu, m.in. że będzie to zestawienie w postaci listy/tabeli
