### ISSUE TITLE
Stworz-widok-edycji-menu

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Team-Project-Class-Project#24]
## Kryteria akceptacji

- [x] widok edycji menu został utworzony
- [x] zaimplementowana została możliwość dodawania pozycji do menu
- [x] zaimplementowana została możliwość usuwania pozycji z menu
- [x] testy widoku zostały dodane
- [ ] zmiany znajdują się na branchu `main`

**Comment by Tomasz-Zdeb** [comment]
W miarę pracy dodaj proszę bardziej szczegółowe kryteria akceptacji
