### ISSUE TITLE
Zainicjuj-baze-danych

### ISSUE THREAD

**Issue by ZimmerPM** [Tomasz-Zdeb/Team-Project-Class-Project#28]
Utworzenie bazy danych

## Kryteria akceptacji
- [x] skonfigurowano kontener bazy danych w Dockerze
- [x] baza danych w SZBD MariaDB została utworzona
- [x] dodano tabelę zawierającą użytkowników
- [x] dodano tabelę zawierającą produkty
- [x] przetestowano CRUD

**Comment by Tomasz-Zdeb** [comment]
bardzo ładne kryteria akceptacji, super! wiadomo dokładnie co ma być zrobione 😀

**Comment by Tomasz-Zdeb** [comment]
@ZimmerPM pamiętaj o nazewnictwie zadań, które jest zdefiniowane w [README.md](https://github.com/Tomasz-Zdeb/Team-Project-Class-Project/blob/main/README.md)

Fragment:
> 
    Zadania definiujemy według ścisłego formatu:
        Nazwa zadania zaczyna się od wielkiej litery pozostałe słowa pisane są małą literą niezależnie czy to nazwy własne czy nie
        Spacje w nazwie zadania są zastąpione myślnikami
        W nazwie zadania nie używamy polskich znaków (wyjaśnienie dlaczego, przy sekcji dotyczącej -branchingu*)
        Opis zadania zawiera kryteria akceptacj czyli stwierdzenia opisujące stan po realizacji zadania na które można odpowiedzieć: prawda lub fałsz wg. formy przedstawionej na zrzucie ekranu (nagłówek drugiego poziomu i checkboxy), które w miarę realizacji zadania oznacza się jako zrealizowane


Chodzi tu o myślniki i polskie znaki, zajrzyj też do reguł nazewnictwa gałęzi, tam też bez polskich znaków

**Comment by Tomasz-Zdeb** [comment]
@ZimmerPM Plus jak pracujesz nad danym taskiem to proszę przypisuj się do niego. Jedna osoba może task stworzyć, inna zaimplementować. Dzięki! 😉
