### ISSUE TITLE
Skonfiguruj-gh-action-usuwajacy-galaz-po-zamknieciu-pr

### ISSUE THREAD

**Issue by WiolaWysopal** [Tomasz-Zdeb/Team-Project-Class-Project#31]
## Kryteria Akceptacji
- [x] Action zostało skonfigurowane
- [x] Action zostało przetestowane
- [x] Action jest uruchamiane tylko przy zmergowanych pull requestach
- [x] Action usuwa branch który został zmergowany

**Comment by WiolaWysopal** [comment]
@Tomasz-Zdeb Wygląda to trochę jakby action nie miało uprawnień, zobacz proszę czy w ustawieniach nie ma czegoś co mogłoby uniemożliwiać wykonanie action

![image](https://github.com/Tomasz-Zdeb/Team-Project-Class-Project/assets/115031260/8a65a53a-a4fe-4a27-a0c2-50d9bb3a7d7d)

**Comment by Tomasz-Zdeb** [comment]
### Było:
![image](https://github.com/Tomasz-Zdeb/Team-Project-Class-Project/assets/62356875/f840da2e-3d35-40cd-8489-6debed287251)
### Zmieniłem na:
![image](https://github.com/Tomasz-Zdeb/Team-Project-Class-Project/assets/62356875/d6554b2a-70bb-459c-82c1-688731ec4a95)

**Comment by WiolaWysopal** [comment]
Chyba teraz się udało :)
![image](https://github.com/Tomasz-Zdeb/Team-Project-Class-Project/assets/115031260/85730cef-1d18-450e-a754-deebba23dcd2)

**Comment by WiolaWysopal** [comment]
![image](https://github.com/Tomasz-Zdeb/Team-Project-Class-Project/assets/115031260/88799d71-892c-45f8-aa48-712a086377ba)
