### ISSUE TITLE
Wybierz-technologie-dla-frontendu

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Team-Project-Class-Project#5]
## Kryteria akceptacji
- [x] Technologie dla frontendu zostały zaproponowane
- [x] Technologie dla frontendu zostały uzasadnione
- [x] Technologie dla frontendu zostały wybrane

**Comment by jackpie2** [comment]
# React
Proponowałbym użycie Reacta, z następujących względów:
- biblioteka jest dość prosta, a tworzenie w niej interaktywnych interfejsów jest stosunkowo szybkie
- bogaty ekosystem i duże wsparcie, react jest najpopularniejszą biblioteką tego typu

Uważam, że React jest odpowiednią biblioteką przy tworzeniu aplikacji o stopniu złożoności i funkcjach, które planujemy. Uważam też, że jego sporą zaletą jest również czytelność, ponieważ tworzone komponenty bazują w większości na składni zwykłego HTMLa, co może ułatwić współpracę. 

# TailwindCSS
Do stylowania proponuję użyć [TailwindCSS](https://tailwindcss.com/), dostarcza on atomowe i niskopoziomowe klasy, pozwalające na definiowanie stylów bezpośrednio w markupie. Główne zalety tego rozwiązania:
- stylowanie z tailwindem jest szybsze niż pisanie CSSa ręcznie, a style są łatwiejsze w utrzymaniu
- w związku z charakterystyką aplikacji, nie ma potrzeby tworzyć bardzo złożonego stylu aplikacji, dlatego użycie prostego frameworka oferującego jedynie style wydaje się lepszym rozwiązaniem, niż używanie bardziej rozbudowanego rozwiązania (np. bootstrap), które wprowadza wiele zbędnych dla projektu komponentów
- styl aplikacji możemy w łatwy sposób dopasować precyzyjnie do naszych potrzeb, bez konieczności walki z frameworkiem i nadpisywaniem styli gotowych komponentów

**Comment by Tomasz-Zdeb** [comment]
Super, brzmi bardzo dobrze. Kojarzę Tailwinda z czasu gdy byłem na stażu, bardzo fajny framework do stylowania, dla którego jest bardzo dużo template w internecie, wiele oczywiście darmowych. Można iść dalej z frontendem 👍🏻
